"""
Capability router — detects when a chat message is actually a structured
request for a specialised service (image generation, code, translation)
and handles it inline rather than passing to the LLM directly.

Returns a formatted string response if routed, or None if the message
should proceed to normal chat handling.
"""
import re

# ── Patterns ──────────────────────────────────────────────────────────────────

_IMAGE_RE = re.compile(
    r"\b(generate|create|draw|make|design|paint)\s+.{0,60}(image|picture|photo|illustration|artwork|poster|logo)\b",
    re.IGNORECASE,
)

_CODE_RE = re.compile(
    r"\b(write|generate|create|build|code|implement|make)\s+.{0,40}(code|function|script|program|class|api|endpoint)\b"
    r"|\b(in python|in javascript|in typescript|in java|in go|in rust|in php|in c\+\+|in sql)\b",
    re.IGNORECASE,
)

_TRANSLATE_RE = re.compile(
    r"\btranslate\s+.{0,100}\s+to\s+\w+\b"
    r"|\btranslate\s+this\s+to\b"
    r"|\bin\s+(french|spanish|german|arabic|twi|hausa|yoruba|swahili|portuguese|chinese|japanese|korean)\b",
    re.IGNORECASE,
)


# ── Target language extractor ─────────────────────────────────────────────────

_LANG_NAMES: dict[str, str] = {
    "french": "fr", "spanish": "es", "german": "de", "arabic": "ar",
    "twi": "ak", "hausa": "ha", "yoruba": "yo", "swahili": "sw",
    "portuguese": "pt", "chinese": "zh", "japanese": "ja", "korean": "ko",
    "english": "en", "italian": "it", "dutch": "nl", "russian": "ru",
}


def _extract_target_lang(message: str) -> str:
    m = re.search(r"\bto\s+(\w+)\b", message, re.IGNORECASE)
    if m:
        lang_word = m.group(1).lower()
        return _LANG_NAMES.get(lang_word, lang_word)
    for lang_word, code in _LANG_NAMES.items():
        if lang_word in message.lower():
            return code
    return "en"


def _extract_text_to_translate(message: str) -> str:
    """Pull the quoted or following text from the message."""
    quoted = re.search(r'["\u201c](.*?)["\u201d]', message)
    if quoted:
        return quoted.group(1)
    # Strip trigger words
    cleaned = re.sub(
        r"translate\s+(this\s+)?(to\s+\w+)?\s*:?\s*",
        "", message, flags=re.IGNORECASE
    ).strip()
    return cleaned if len(cleaned) > 3 else ""


# ── Router ────────────────────────────────────────────────────────────────────

async def route_capability(message: str):
    """
    Returns a string response if this message is handled by a specialised
    service, or None if it should go to normal chat inference.
    """
    # Image generation
    if _IMAGE_RE.search(message):
        try:
            from services.image_gen_service import generate_image
            import base64
            image_bytes, provider, seed = await generate_image(prompt=message)
            if image_bytes:
                b64 = base64.b64encode(image_bytes).decode()
                return (
                    f"![Generated image](data:image/png;base64,{b64})\n\n"
                    f"_Generated by {provider} · seed {seed}_"
                )
        except Exception:
            pass
        return None  # fall through to chat if image gen fails

    # Code generation
    if _CODE_RE.search(message):
        try:
            from services.code_service import generate_code
            code, language, explanation, provider, model = await generate_code(
                prompt=message, language="", context="", max_tokens=2048
            )
            if code:
                lang_label = language or "code"
                response = f"```{lang_label}\n{code}\n```"
                if explanation:
                    response += f"\n\n{explanation}"
                return response
        except Exception:
            pass
        return None

    # Translation
    if _TRANSLATE_RE.search(message):
        text_to_translate = _extract_text_to_translate(message)
        if text_to_translate and len(text_to_translate) > 5:
            try:
                from services.translation_service import translate
                target_lang = _extract_target_lang(message)
                translated, source, provider = await translate(
                    text=text_to_translate, target_lang=target_lang
                )
                if translated:
                    return f'**Translation ({source} → {target_lang}):**\n\n{translated}\n\n_via {provider}_'
            except Exception:
                pass
        return None

    return None
